"""Normalise category & author into master tables with FKs.

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-23

Replaces the free-text ``articles.category`` / ``articles.author`` columns with
``category_id`` / ``author_id`` FKs into new ``categories`` / ``authors`` master
tables (review item: normalisation). On a fresh DB the backfill UPDATEs are
no-ops (articles is empty until ingest); on an existing DB they migrate data.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Master tables
    op.execute(
        "CREATE TABLE categories ("
        "id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "name TEXT UNIQUE NOT NULL);"
    )
    op.execute(
        "CREATE TABLE authors ("
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "name TEXT UNIQUE NOT NULL);"
    )

    # Seed the fixed category vocabulary; authors are derived from existing data.
    op.execute(
        "INSERT INTO categories(name) VALUES ('AI/ML'),('Backend'),('Frontend'),('DevOps');"
    )
    op.execute("INSERT INTO authors(name) SELECT DISTINCT author FROM articles;")

    # Add FK columns, backfill, then enforce NOT NULL.
    op.execute("ALTER TABLE articles ADD COLUMN category_id SMALLINT REFERENCES categories(id);")
    op.execute("ALTER TABLE articles ADD COLUMN author_id INTEGER REFERENCES authors(id);")
    op.execute("UPDATE articles a SET category_id = c.id FROM categories c WHERE c.name = a.category;")
    op.execute("UPDATE articles a SET author_id = au.id FROM authors au WHERE au.name = a.author;")
    op.execute("ALTER TABLE articles ALTER COLUMN category_id SET NOT NULL;")
    op.execute("ALTER TABLE articles ALTER COLUMN author_id SET NOT NULL;")

    # Remove old text-column artefacts (indexes/constraint), then the columns.
    op.execute("DROP INDEX IF EXISTS idx_articles_category;")
    op.execute("DROP INDEX IF EXISTS idx_articles_author;")
    op.execute("DROP INDEX IF EXISTS idx_articles_category_published;")
    op.execute("ALTER TABLE articles DROP CONSTRAINT IF EXISTS ck_articles_category;")
    op.execute("ALTER TABLE articles DROP COLUMN category;")
    op.execute("ALTER TABLE articles DROP COLUMN author;")

    # Indexes on the new FK columns (facet filter + sort).
    op.execute("CREATE INDEX idx_articles_category_id ON articles(category_id);")
    op.execute("CREATE INDEX idx_articles_author_id ON articles(author_id);")
    op.execute(
        "CREATE INDEX idx_articles_catid_published ON articles(category_id, published_at DESC);"
    )


def downgrade() -> None:
    # Recreate text columns and backfill from master tables.
    op.execute("ALTER TABLE articles ADD COLUMN category TEXT;")
    op.execute("ALTER TABLE articles ADD COLUMN author TEXT;")
    op.execute("UPDATE articles a SET category = c.name FROM categories c WHERE c.id = a.category_id;")
    op.execute("UPDATE articles a SET author = au.name FROM authors au WHERE au.id = a.author_id;")
    op.execute("ALTER TABLE articles ALTER COLUMN category SET NOT NULL;")
    op.execute("ALTER TABLE articles ALTER COLUMN author SET NOT NULL;")

    op.execute("DROP INDEX IF EXISTS idx_articles_catid_published;")
    op.execute("DROP INDEX IF EXISTS idx_articles_author_id;")
    op.execute("DROP INDEX IF EXISTS idx_articles_category_id;")
    op.execute("ALTER TABLE articles DROP COLUMN category_id;")
    op.execute("ALTER TABLE articles DROP COLUMN author_id;")
    op.execute("DROP TABLE IF EXISTS authors;")
    op.execute("DROP TABLE IF EXISTS categories;")

    # Restore 0002 artefacts.
    op.execute(
        "ALTER TABLE articles ADD CONSTRAINT ck_articles_category "
        "CHECK (category IN ('AI/ML', 'Backend', 'Frontend', 'DevOps'));"
    )
    op.execute("CREATE INDEX idx_articles_category ON articles (category);")
    op.execute("CREATE INDEX idx_articles_author ON articles (author);")
    op.execute(
        "CREATE INDEX idx_articles_category_published ON articles (category, published_at DESC);"
    )
